cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_summary, name='cart_summary'),
    path('add/', views.add_cart, name='add_cart'),
    path('delete/', views.delete_cart, name='cart_delete'),
    path('update/', views.update_cart, name='cart_update')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('', include('homepage.urls')),
    path('cart', include('cart.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *
from .forms import LoginForm
app_name = 'homepage'

urlpatterns = [
    path('', index, name= 'index'),
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='homepage/signin.html', authentication_form=LoginForm), name='login'),
    path('logout/', logOut, name='logout')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('store/', views.store, name='store'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete')
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class HeadphoneType(models.Model):
    name = models.CharField(max_length = 255)

    class Meta:
        ordering = ('name',)
    
    def __str__(self) -> str:
        return self.name
    


class Headphone(models.Model):
    htype = models.ForeignKey(HeadphoneType, related_name = 'items', on_delete = models.CASCADE)
    name = models.CharField(max_length = 255)
    specs = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)


    def __str__(self) -> str:
        return self.name

homepage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2' )
       
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':' py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email',
        'class':' py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Password',
        'class':' py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Retype Password',
        'class':' py-4 px-6 rounded-xl'
    }))




class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':' py-4 px-6 rounded-xl'
    }), required=True)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Password',
        'class':' py-4 px-6 rounded-xl'
    }), required=True)

cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from store.models import Headphone
from django.http import JsonResponse
# Create your views here.

def cart_summary(request):
    cart = Cart(request)
    cart_prods = cart.get_prods
    quantities = cart.get_quants
    return render(request, 'cart/summary.html', {'cart_items':cart_prods, 'quantities':quantities})

def add_cart(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(Headphone, id = product_id) #getting product
        cart.add(product=product, quantity = product_qty) #saving to cart
        # getting cart quantity
        cart_quantity = cart.__len__()
        response = JsonResponse({
            'qty':cart_quantity
            })

        return response



def delete_cart(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        cart.delete(product=product_id)
        
        
        response = JsonResponse({'product':product_id})
        return response



def update_cart(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        cart.update(product=product_id, quantity=product_qty)

        response = JsonResponse({'qty':product_qty})
        return response

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from store.models import *

from . import forms
# Create your views here.
def index(request):
    category = HeadphoneType.objects.all()
    return render(request, 'homepage/index.html', {
        'categories': category
    })

def signup(request):
    if request.method == 'POST':
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = forms.SignupForm
        return render(request, 'homepage/signup.html', {
            'form':form
        })
        


def logOut(request):
    logout(request)
    return redirect('/login/')

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Headphone
from cart.cart import Cart

def store(request):
    items = Headphone.objects.all()
    return render(request, 'store/store.html', {
        'items':items
    })

def detail(request ,pk):
    cart = Cart(request)
    cart_items = cart.get_prods
    item = get_object_or_404(Headphone, pk=pk)
    related_items = Headphone.objects.filter(htype = item.htype).exclude(pk=pk)[0:2]
    return render(request, 'store/itemdetail.html', {
        'product':item,
        'similar':related_items,
        'cart_items':cart_items
    })

@login_required

def delete(request, pk):
    item = get_object_or_404(Headphone, pk=pk, created_by=request.user)
    item.delete()

    return redirect('homepage:index')

cart/templates/cart/summary.html
{% extends 'homepage/landing.html' %}
{% block title %} Cart {% endblock %}
{% block content %}
{% if cart_items %}
<div class="mt-6 px-6 py-12 bg-white rounded-xl">
    <h2 class="mb-8 text-5xl text-center">My Cart</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
        {% for item in cart_items %}
        <div>
            <div class="p-6 bg-gray-100 rounded-xl">
                <a href="{% url 'store:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div>
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-black-500">Price: N{{ item.price }}</p>
                        <div class="my-5">
                        </div>
                    </div>
                </a>
                <div class="my-5">
                    <select id="select{{ item.id }}" class="bg-gray-800 border border-gray-800 text-gray-900 text-sm rounded-lg focus:ring-gray-800 focus:border-gray-800 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-800 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-800 dark:focus:border-gray-800">
                        <option selected>
                            {% for key, value in quantities.items %}
                                {% if key == item.id|slugify %}
                                    {{ value }}
                                {% endif %}
                            {% endfor %}
                        </option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select> 
                </div>
                <div class="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                    <div class="items-center col-span-1 sm:col-span-1 md:col-span-1 lg:col-span-2">
                        <button type="button" data-index="{{ item.id }}" class="update-cart  inline-block mt-6 px-6 py-3 mb-3 mx-4 text-md font-semibold text-white bg-gray-800 hover:br-gray-600 rounded-lg">
                            Update
                        </button>
                    </div>
                    <div class="items-center col-span-1 sm:col-span-1 md:col-span-1 lg:col-span-2">
                        <button type="button" data-index="{{ item.id }}" class="delete-item inline-block mt-6 px-6 py-3 mb-3 mx-4 text-md font-semibold text-white bg-red-600 hover:br-gray-600 rounded-lg">
                            Remove
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% else %}
<h1 class="text-base text-4xl text-center m-10">
    There's nothing in your cart
</h1>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endif %}

<script>
    // update cart
    $(document).on('click', '.update-cart', function(e){
        e.preventDefault();
        var productid = $(this).data('index');
        $.ajax({
            type:'POST',
            url:"{% url 'cart:cart_update' %}",
            data:{
                product_id: $(this).data('index'),
                product_qty: $('#select' + productid + ' option:selected').text(),
                csrfmiddlewaretoken:'{{ csrf_token }}',
                action:'post'
            },
            success: function(json) {
                // console.log(json)
                // document.getElementById('cart_qty').textContent = (json.qty)
                window.location.reload()
            },
            error: function(xhr, errmsg, err) {
                
            }
        });
        window.location.reload()
    });

    // delete item from cart
    $(document).on('click', '.delete-item', function(e){
        e.preventDefault();
        var productid = $(this).data('index');
        $.ajax({
            type:'POST',
            url:"{% url 'cart:cart_delete' %}",
            data:{
                product_id: $(this).data('index'),
                csrfmiddlewaretoken:'{{ csrf_token }}',
                action:'post'
            },
            success: function(json) {
                // console.log(json)
                // document.getElementById('cart_qty').textContent = (json.qty)
                window.location.reload()
            },
            error: function(xhr, errmsg, err) {
                
            }
        });
        window.location.reload()
    });
</script>
{% endblock %}

homepage/templates/homepage/index.html
{% extends 'homepage/landing.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="items-center">
        <h1 class= "text-center text-2-xl font-semibold text-gray-100">the home page</h1>
    </div>
    <div class="min-h-screen flex flex-col justify-center lg:flex-row items-center lg:justify-between lg:px-30 px-5">       
        <div class="w-full lg:w-2/4 space-y-4 mt-20">
            <div class="text-5xl font-semibold leading-tight">Discover Next-Level Audio Experiences</div> <br>           
            <p>Beats offer a variety of headphones, including over-ear, on-ear, and earbuds.
                Beats headphones are known for their bass-heavy sound profile, which is popular with many music lovers.</p><br>
                <a href="{% url 'store:store' %}" class="inline-block mt-6 px-6 py-3 text-md font-semibold bg-gray-800 text-white hover:bg-gray-600 rounded-lg">Buy Now</a>

        </div>
        <div class="mt-10">
            <a href=""><img src="https://i.ibb.co/7zMXnsm/brown-01-cnet-jpg-large-2x.jpg"></a><br /><a target='_blank'></a><br />
        </div>
    </div>
    
    <div class="">
        
        <div class="mt-6 px-6 py-12 bg-white rounded-xl">
            <h2 class="font-semibold text-5xl py-7 text-center ">Popular Now</h2>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                {% for category in categories %}
                    <div>
                        <a href="{% url 'store:store' %}">
                            <div class="p-6 bg-gray-100 rounded-xl">
                                <h2 class="text-xl text-center">{{ category.name }}</h2>
                                <p class="text-black text-center">{{ category.items.count }} Item(s)</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

homepage/templates/homepage/landing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</head>

<body class="bg-white">
    <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center justify-between">
                <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                    <!-- Mobile menu button-->
                    <button type="button"
                        class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                        aria-controls="mobile-menu" aria-expanded="false">
                        <span class="absolute -inset-0.5"></span>
                        <span class="sr-only">Open main menu</span>
                        <!--
                    Icon when menu is closed.
        
                    Menu open: "hidden", Menu closed: "block"
                  -->
                        <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                        </svg>
                        <!--
                    Icon when menu is open.
        
                    Menu open: "block", Menu closed: "hidden"
                  -->
                        <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                    <div class="flex flex-shrink-0 items-center">
                        <a href="/">
                            <p class="text-lg text-bold text-white">Beats.com</p>
                        </a>
                    </div>
                    <div class="hidden sm:ml-6 sm:block">
                        <div class="flex space-x-4">
                            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                            <a href="/"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
                                aria-current="page">Home</a>
                            <a href="{% url 'store:store' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Shop
                                Now</a>
                            <a href="{% url 'cart:cart_summary' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Checkout
                                <span class="text-white" id="cart_qty">({{ cart|length }})</span></a>
                        </div>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">


                    <!-- Profile dropdown -->
                    <div class="relative ml-3">
                        <div>
                            <button type="button"
                                class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                                id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <span class="absolute -inset-1.5"></span>
                                <span class="sr-only">Open user menu</span>
                                <!-- <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt=""> -->
                                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"
                                    class="h-8 w-8 rounded-xl">
                                    <path
                                        d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z" />
                                </svg>
                            </button>
                        </div>

                        <!--
                    Dropdown menu, show/hide based on menu state.
        
                    Entering: "transition ease-out duration-100"
                      From: "transform opacity-0 scale-95"
                      To: "transform opacity-100 scale-100"
                    Leaving: "transition ease-in duration-75"
                      From: "transform opacity-100 scale-100"
                      To: "transform opacity-0 scale-95"
                  -->
                        <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-gray-900 py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden"
                            id="user-menu" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button"
                            tabindex="-1">
                            <!-- Active: "bg-gray-100", Not Active: "" -->
                            {% if request.user.is_staff %}
                            <a href="#" class="block px-4 py-2 text-sm text-white" role="menuitem" tabindex="-1"
                                id="user-menu-item-0">Seller Profile</a>
                            {% else %}
                            <a href="#" class="block px-4 py-2 text-sm text-white" role="menuitem" tabindex="-1"
                                id="user-menu-item-0">Your Profile</a>
                            {% endif %}
                            <a href="{% url 'cart:cart_summary' %}" class="block px-4 py-2 text-sm text-white" role="menuitem" tabindex="-1"
                                id="user-menu-item-1">Checkout <span class="text-white" id="cart_qty">({{ cart|length }})</span></a>
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'homepage:logout' %}" class="block px-4 py-2 text-sm text-white" role="menuitem" tabindex="-1"
                                id="user-menu-item-2">Sign out</a>
                            {% else %}
                            <a href="{% url 'homepage:login' %}" class="block px-4 py-2 text-sm text-white" role="menuitem" tabindex="-1"
                                id="user-menu-item-2">Sign in</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden hidden fade-in" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <a href="/"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
                    aria-current="page">Home</a>
                <a href="{% url 'store:store' %}"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
                    aria-current="page">Shop now</a>
            </div>
    </nav>
    <style>
        /* Define fade-in animation */
        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes dropDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Apply animation to the mobile menu */
        .fade-in {
            animation: fadeIn 0.3s ease-in-out;
        }
    </style>
    <script>
        // Function to handle dropdown menu visibility toggle
        function toggleDropdownMenu(menuId) {
            const menu = document.getElementById(menuId);
            if (menu.classList.contains("hidden")) {
                // Show the menu
                menu.classList.remove("hidden");
                menu.classList.add("block");
            } else {
                // Hide the menu
                menu.classList.remove("block");
                menu.classList.add("hidden");
            }
        }

        // Event listeners for dropdown buttons
        const userMenuButton = document.getElementById("user-menu-button");
        const mobileMenuButton = document.querySelector(
            '[aria-controls="mobile-menu"]'
        );

        userMenuButton.addEventListener("click", function () {
            toggleDropdownMenu("user-menu");
        });

        mobileMenuButton.addEventListener("click", function () {
            toggleDropdownMenu("mobile-menu");
        });
    </script>


    {% block content %} {% endblock %}
    <footer class="py-6 px-6 flex justify-between bg-gray-800 font-sans">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-white">
                About
            </h3>
            <p class="text-lg text-white">
                Beats by Dr. Dre (Beats) is a leading audio brand founded in 2006 by Dr. Dre and Jimmy Iovine.
            </p>
            <a href="https://twitter.com/rokarioss1" class="text-sm text-white hover:text-gray-100">Website By: @rokarioss1(twitter)</a><br>
            <a href="https://github.com/rokari-19" class="text-sm text-white hover:text-gray-100">rokari-19(github)</a>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-white">Menu</h3>
            <ul class="space-y-2">
                <span class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                    {% if request.user.is_authenticated %}
                    {% else %}
                    <li><a href="{% url 'homepage:signup' %}" class="text-lg text-white">Create an Account</a></li>
                    {% endif %}
                    <li><a href="#" class="text-lg text-white">Socials</a></li>
                    <li><a href="#" class="text-lg text-white">FAQs</a></li>
                    <li><a href="" class="text-lg text-white">Contact</a></li>
                    <li><a href="#" class="text-lg text-white">Terms Of Use</a></li>
                </span>
            </ul>
        </div>
    </footer>
</body>

</html>

homepage/templates/homepage/signin.html
{% extends 'homepage/landing.html' %}

{% block title %}Sign In To Your Account{% endblock %}

{% block content %}
<div>
    <h1 class="text-center text-5xl font-semibold text-base">
      
    </h1>
    <div class="flex justify-center items-center px-6 py-6 ">
      <form action="." method="post" class="bg-white shadow-md rounded-xl px-8 pt-6 pb-8 mb-4 w-full sm:w-1/2 lg:w-1/3">
          {% csrf_token %}
        <div class="mb-6">
          <label class="block text-gray-700 text-sm font-bold mb-2 items-center" for="password">
            Username
          </label>
          <!-- <input
            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
            id="password" type="password" placeholder="********"> -->
            {{ form.username }}
        </div>
        <div class="mb-6">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
            Type A Password
          </label>
            {{ form.password }}
        </div>
          {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-3 bg-red-100 rounded-xl">
            {% for field in form  %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
          </div>
          {% endif %}
        <button class="py-3 px-3 mx-auto text-lg rounded-xl text-white bg-gray-800 ">Sign in</button>
      </form>
    </div>
  </div>
{% endblock %}

store/templates/store/itemdetail.html
{% extends 'homepage/landing.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
    {% if product.image.url %}
    <div class="col-auto sm:col-auto md:col-span-2 lg:col-span-2">
        <img src="{{ product.image.url }}" class="rounded-lg">
    </div>
    {% endif %}
    <div class="col-auto sm:col-auto md:col-span-1 lg:col-span-2 bg-white rounded-xl px-5 py-4">
        <h1 class="mb-6 text-3xl text-black">{{ product.name }}</h1>
        <p class="text-black"><strong>Price: </strong>{{ product.price }}</p>
        <!-- <p class="text-black-500"><strong>Seller: </strong>{{ product.created_by }}</p> -->
        {% if product in cart_items %}
            <button  value="{{ product.id }}" class="bg-gray-800 inline-block mt-6 px-6 py-3 mb-3 text-md font-semibold text-white rounded-lg">
                Added To Cart
            </button>
            <button type="button" data-index="{{ product.id }}" class="inline-block mt-6 px-6 py-3 mb-3 text-md font-semibold text-white bg-gray-800 hover:br-gray-600 rounded-lg update-cart">
                Update
            </button>
        {% else %}
            <a href="#" class="inline-block mt-6 px-6 py-3 text-md font-semibold bg-gray-800 text-white hover:bg-gray-600 rounded-lg">Buy Now</a>
            <button id="add-cart" value="{{ product.id }}" class="inline-block mt-6 px-6 py-3 mb-3 text-md font-semibold bg-gray-800 text-white hover:bg-gray-600 rounded-lg">
                Add To Cart
            </button>
        {% endif %}
        <select id="qty_cart" class="select{{ product.id }} bg-gray-800 border border-gray-800 text-gray-900 text-sm rounded-lg focus:ring-gray-800 focus:border-gray-800 block w-full    p-2.5 dark:bg-gray-800 dark:border-gray-800 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-800 dark:focus:border-gray-800">
            <option value="">Select Quantity</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>   
        {% if product.specs %}
            <p class="text-gray-500">
                <strong class="text-gray-900">Details: </strong><br>
                {{ product.specs }}
                
            </p>
        {% endif %}
    </div>
</div>

<script>
    $(document).on('click', '#add-cart', function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:"{% url 'cart:add_cart' %}",
            data:{
                product_id: $('#add-cart').val(),
                product_qty: $('#qty_cart option:selected').text(),
                csrfmiddlewaretoken:'{{ csrf_token }}',
                action:'post'
            },
            success: function(json) {
                // console.log(json)
                document.getElementById('cart_qty').textContent = (json.qty)
            },
            error: function(xhr, errmsg, err) {
                
            }
        });
        window.location.reload()
    });
</script>
{% endblock %}

store/templates/store/store.html
{% extends 'homepage/landing.html' %}

{% block title %}Store{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-white rounded-xl">
    <h2 class="mb-8 text-5xl text-center">Popular now</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'store:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-gray-100 rounded-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-black-500">Price: N{{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}